### ISSUE TITLE
Auto-Totem minimum health

### ISSUE THREAD

**Issue by axberfanaccount** [THEREALWWEFAN231/Inertia#485] opened 2020-04-01 00:34 UTC
all

so you can hold something else in your offhand and when you reach a certain amount of health it will equip the totem 

to add more diversity to players playstyles

**Comment by cookiedragon234** [comment] 2020-04-27 10:49
Minimum or maximum? 🤨

**Comment by Paralusion** [comment] 2021-04-17 21:30
duplicate of some issue

**Closed by Paralusion** 2021-04-17 21:30 UTC
Labels: enhancement
