### ISSUE TITLE
Mob Spawn ESP

### ISSUE THREAD

**Issue by JoshuaAllenby** [THEREALWWEFAN231/Inertia#294] opened 2019-09-04 07:10 UTC
**Minecraft Version**
1.14.4 (Or any)
**What is the suggestion**
Mob spawn ESP - show where mobs can spawn.
**Why it will be useful**
It would save a lot of time checking light levels on the F3 menu.

WURST client has this feature and it's super useful.
![45874628-ac1a9480-bd95-11e8-86d4-266d7981ff0d](https://user-images.githubusercontent.com/42005484/64233169-60e88b80-ceeb-11e9-8684-249539b21f8c.jpg)

**Comment by BleachDrinker420** [comment] 2019-09-04 11:12
duplicate of #113 , also wurst didn't come up with this feature, NEI had the exact same thing but that isn't for 1.13+ anyways

**Comment by JoshuaAllenby** [comment] 2019-09-04 11:51
> duplicate of #113 , also wurst didn't come up with this feature, NEI had the exact same thing but that isn't for 1.13+ anyways

Never claimed they came up with the feature - this feature has existed for ages. I referenced them as they have a client for 1.14.4 that includes this feature.  My mistake of making a duplication.

**Closed** 2021-01-27 19:55 UTC
