### ISSUE TITLE
Shield Bot

### ISSUE THREAD

**Issue by jackbugler** [THEREALWWEFAN231/Inertia#770] opened 2020-10-05 21:07 UTC
**Minecraft Version(s)**
1.16.3/1.17
**What is the suggestion**
 Shield Bot
**Why would this feature be useful**
With KA, you can't get hit by a sword because enemies can't get close enough, sure.
But what about arrows and other projectiles? It's not like you can just slash an arrow in half.
What I'm saying is, there should be an automatic shield module to attempt to prevent ranged attacks as well.
The settings would be things like a range selector for how far away we should lock onto arrows, a selector for client/packet rotations, etc.

**Comment by MLGgamingpro** [comment] 2020-10-09 21:57
Duplicate of #738 #636 #492 and #116
You can see my opinion in #738.
`"While this feature would be useful, I think it would be difficult to implement (for arrows) since it would have to predict where the arrow is going, and block in time, and you will also probably be moving while it happens. For creepers i don't think it would be to difficult since it would have to block when a creeper is in your radius. For now just turn on the option that shows sounds in the bottom left, or just use NoSlow and always block."`

**Comment by Paralusion** [comment] 2021-04-17 19:41
duplicate of #116

**Closed by Paralusion** 2021-04-17 19:41 UTC
Labels: enhancement
