### ISSUE TITLE
Phase Module

### ISSUE THREAD

**Issue by oofmas** [THEREALWWEFAN231/Inertia#597] opened 2020-08-02 02:10 UTC
**Minecraft Version(s)** All

**What is the suggestion** Add a phase module which, through various methods, lets you phase through blocks.  

**Why would this feature be useful**
Uses for this module:
1) Area is protected behind blocks you can't go through.
2) You're trapped in a box.
3) You're playing a HCF server and want to get into someone's base. 
4) You want to get into someone's faction base. 
5) Replacing the broken .clip h which doesn't even work on Vanilla servers.

**Comment by Oecher1** [comment] 2020-08-02 13:28
> **Minecraft Version(s)** All
> 
> **What is the suggestion** Add a phase module which, through various methods, lets you phase through blocks.
> 
> **Why would this feature be useful**
> Uses for this module:
> 
> 1. Area is protected behind blocks you can't go through.
> 2. You're trapped in a box.
> 3. You're playing a HCF server and want to get into someone's base.
> 4. You want to get into someone's faction base.
> 5. Replacing the broken .clip h which doesn't even work on Vanilla servers.

3 and 4 i dont really understand as your on 1.12.2 for a 1.7-1.8 hcf server why not use a 1.8 client lol

**Comment by Cypphi** [comment] 2020-08-02 20:10
> 
> 
> **Minecraft Version(s)** All
> 
> **What is the suggestion** Add a phase module which, through various methods, lets you phase through blocks.
> 
> **Why would this feature be useful**
> Uses for this module:
> 
>     1. Area is protected behind blocks you can't go through.
> 
>     2. You're trapped in a box.
> 
>     3. You're playing a HCF server and want to get into someone's base.
> 
>     4. You want to get into someone's faction base.
> 
>     5. Replacing the broken .clip h which doesn't even work on Vanilla servers.

phase is a good idea, but I don't know any client that have working phase for vanilla. So they might have to make their own vanilla bypass which could be very difficult for phase since vanilla sees moving trough a block as a wrong movement.

**Comment by oofmas** [comment] 2020-08-02 21:56
> > **Minecraft Version(s)** All
> > **What is the suggestion** Add a phase module which, through various methods, lets you phase through blocks.
> > **Why would this feature be useful**
> > Uses for this module:
> > ```
> > 1. Area is protected behind blocks you can't go through.
> > 
> > 2. You're trapped in a box.
> > 
> > 3. You're playing a HCF server and want to get into someone's base.
> > 
> > 4. You want to get into someone's faction base.
> > 
> > 5. Replacing the broken .clip h which doesn't even work on Vanilla servers.
> > ```
> 
> phase is a good idea, but I don't know any client that have working phase for vanilla. So they might have to make their own vanilla bypass which could be very difficult for phase since vanilla sees moving trough a block as a wrong movement.

Literally every hacked client has phase lmao.

**Comment by Cypphi** [comment] 2020-08-03 10:13
> 
> 
> > > **Minecraft Version(s)** All
> > > **What is the suggestion** Add a phase module which, through various methods, lets you phase through blocks.
> > > **Why would this feature be useful**
> > > Uses for this module:
> > > ```
> > > 1. Area is protected behind blocks you can't go through.
> > > 
> > > 2. You're trapped in a box.
> > > 
> > > 3. You're playing a HCF server and want to get into someone's base.
> > > 
> > > 4. You want to get into someone's faction base.
> > > 
> > > 5. Replacing the broken .clip h which doesn't even work on Vanilla servers.
> > > ```
> > 
> > 
> > phase is a good idea, but I don't know any client that have working phase for vanilla. So they might have to make their own vanilla bypass which could be very difficult for phase since vanilla sees moving trough a block as a wrong movement.
> 
> Literally every hacked client has phase lmao.

but most if not all don't work for vanilla, most of them are things like NCP bypasses or for hypixel only. I know many phase modules but most of em are for hypixel

**Comment by oofmas** [comment] 2020-08-03 19:27
> > > > **Minecraft Version(s)** All
> > > > **What is the suggestion** Add a phase module which, through various methods, lets you phase through blocks.
> > > > **Why would this feature be useful**
> > > > Uses for this module:
> > > > ```
> > > > 1. Area is protected behind blocks you can't go through.
> > > > 
> > > > 2. You're trapped in a box.
> > > > 
> > > > 3. You're playing a HCF server and want to get into someone's base.
> > > > 
> > > > 4. You want to get into someone's faction base.
> > > > 
> > > > 5. Replacing the broken .clip h which doesn't even work on Vanilla servers.
> > > > ```
> > > 
> > > 
> > > phase is a good idea, but I don't know any client that have working phase for vanilla. So they might have to make their own vanilla bypass which could be very difficult for phase since vanilla sees moving trough a block as a wrong movement.
> > 
> > 
> > Literally every hacked client has phase lmao.
> 
> but most if not all don't work for vanilla, most of them are things like NCP bypasses or for hypixel only. I know many phase modules but most of em are for hypixel

i've seen hypixel phase modules but never 2 in the same client or it being the only mode, I usually see multiple phases for things like NPC, AAC, etc. and then a few which work depending on the situation and what you're trying to phase through, and most of which work on Vanilla.

**Comment by Cypphi** [comment] 2020-08-03 22:46
> > > > > **Minecraft Version(s)** All
> > > > > **What is the suggestion** Add a phase module which, through various methods, lets you phase through blocks.
> > > > > **Why would this feature be useful**
> > > > > Uses for this module:
> > > > > ```
> > > > > 1. Area is protected behind blocks you can't go through.
> > > > > 
> > > > > 2. You're trapped in a box.
> > > > > 
> > > > > 3. You're playing a HCF server and want to get into someone's base.
> > > > > 
> > > > > 4. You want to get into someone's faction base.
> > > > > 
> > > > > 5. Replacing the broken .clip h which doesn't even work on Vanilla servers.
> > > > > ```
> > > > 
> > > > 
> > > > phase is a good idea, but I don't know any client that have working phase for vanilla. So they might have to make their own vanilla bypass which could be very difficult for phase since vanilla sees moving trough a block as a wrong movement.
> > > 
> > > 
> > > Literally every hacked client has phase lmao.
> > 
> > 
> > but most if not all don't work for vanilla, most of them are things like NCP bypasses or for hypixel only. I know many phase modules but most of em are for hypixel
> 
> i've seen hypixel phase modules but never 2 in the same client or it being the only mode, I usually see multiple phases for things like NPC, AAC, etc. and then a few which work depending on the situation and what you're trying to phase through, and most of which work on Vanilla.

Mojang fixed some things which also patched phase, there are bypasses but the NCP or AAC ones don't work because they're made to bypass something non vanilla, if you're right, which clients do you use and which version? I used many clients and never found a bypass

**Comment by oofmas** [comment] 2020-08-05 23:25
> > > > > > **Minecraft Version(s)** All
> > > > > > **What is the suggestion** Add a phase module which, through various methods, lets you phase through blocks.
> > > > > > **Why would this feature be useful**
> > > > > > Uses for this module:
> > > > > > ```
> > > > > > 1. Area is protected behind blocks you can't go through.
> > > > > > 
> > > > > > 2. You're trapped in a box.
> > > > > > 
> > > > > > 3. You're playing a HCF server and want to get into someone's base.
> > > > > > 
> > > > > > 4. You want to get into someone's faction base.
> > > > > > 
> > > > > > 5. Replacing the broken .clip h which doesn't even work on Vanilla servers.
> > > > > > ```
> > > > > 
> > > > > 
> > > > > phase is a good idea, but I don't know any client that have working phase for vanilla. So they might have to make their own vanilla bypass which could be very difficult for phase since vanilla sees moving trough a block as a wrong movement.
> > > > 
> > > > 
> > > > Literally every hacked client has phase lmao.
> > > 
> > > 
> > > but most if not all don't work for vanilla, most of them are things like NCP bypasses or for hypixel only. I know many phase modules but most of em are for hypixel
> > 
> > 
> > i've seen hypixel phase modules but never 2 in the same client or it being the only mode, I usually see multiple phases for things like NPC, AAC, etc. and then a few which work depending on the situation and what you're trying to phase through, and most of which work on Vanilla.
> 
> Mojang fixed some things which also patched phase, there are bypasses but the NCP or AAC ones don't work because they're made to bypass something non vanilla, if you're right, which clients do you use and which version? I used many clients and never found a bypass

Pretty much every single 1.8.9 client has one, but that's 1.8.9. The only 1.9+ clients I've used is Inertia/WWE, but I'm still dead set that a phase module is atleast possible.

**Comment by Paralusion** [comment] 2021-04-17 21:12
duplicate of #433

**Closed by Paralusion** 2021-04-17 21:12 UTC
Labels: enhancement
