### ISSUE TITLE
Suggestion - Special Characters and Colors for Anvil

### ISSUE THREAD

**Issue by aaxzkc** [THEREALWWEFAN231/Inertia#418] opened 2019-12-23 12:11 UTC
There are modules that let you get special characters and colors for signs, but not for anvils. Adding this for anvils will allow people to get swords with colored names and special characters in them, that no one else can get.

**Comment by Paralusion** [comment] 2021-04-17 21:04
duplicate of #236

**Closed by Paralusion** 2021-04-17 21:04 UTC
