### ISSUE TITLE
Suggestion [Don't scaffold with things like fences because it doesnt work

### ISSUE THREAD

**Issue by Hexiro** [THEREALWWEFAN231/Inertia#512] opened 2020-05-12 18:14 UTC
**1.12.2 but really all**

**when use scaffold add an option where scaffold will ignore fences, etc.**

**scaffold with fences doesn't work**

**Comment by Paralusion** [comment] 2021-04-17 18:45
duplicate of #1128

**Closed by Paralusion** 2021-04-17 18:45 UTC
Labels: enhancement
