### ISSUE TITLE
1.16.5Suggestion Add anchor aura for pvp

### ISSUE THREAD

**Issue by qwerrtttttttty** [THEREALWWEFAN231/Inertia#1142] opened 2021-04-03 06:02 UTC
**Minecraft Version(s)**

**What is the suggestion**

**Why would this feature be useful**

**Final checklist:**

- [ ] I know how to properly use check boxes 
- [ ] This is not a suggestion for baritone or other mod

**Comment by THEREALWWEFAN231** [comment] 2021-04-03 06:28
I mean, damn, don't use the template 😳 , this is already planned/added to the 1.16 version, but not yet completed(I mean it works, but I have other plans) but it should be in the next update when ever that is 🤷‍♂️

**Comment by qwerrtttttttty** [comment] 2021-04-03 08:50
can you make the auto totem faster pls


Pada tanggal Sab, 3 Apr 2021 pukul 13.28 THEREALWWEFAN231 <
***@***.***> menulis:

**Comment by feliscatusmeows** [comment] 2021-04-03 16:39
The reason autototem fails is due entirety to ping.

**Comment by qwerrtttttttty** [comment] 2021-04-04 02:47
is there a setting to make the crystal aura auto place and fast

Pada tanggal Sab, 3 Apr 2021 pukul 23.39 feliscatusmeows <
***@***.***> menulis:

**Comment by feliscatusmeows** [comment] 2021-04-04 02:57
:pain: That will be in inertia 3.2.

**Comment by qwerrtttttttty** [comment] 2021-04-04 03:34
when is the update?


Pada tanggal Min, 4 Apr 2021 pukul 09.58 feliscatusmeows <
***@***.***> menulis:

**Comment by feliscatusmeows** [comment] 2021-04-06 04:55
The update will come in the next [0-8974356459267843265864825684625642] hours. Please be patient.

**Comment by Paralusion** [comment] 2021-04-17 17:44
duplicate of #922 and already planned

**Closed by Paralusion** 2021-04-17 17:44 UTC
Labels: enhancement
