### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by HyperAzur** [THEREALWWEFAN231/Inertia#70] opened 2019-07-07 17:51 UTC
**Minecraft Version**
          1.14.3

**What is the suggestion** 
Remove wwe accents from client. Like wwe button from homescreen and login/name from multiplayer screen.
Ingame add a panic button to suspend all keybindings.
Add a turn off all modules.

**Why it will be useful** 
**Proving innocence.**

**Comment by Paralusion** [comment] 2021-04-17 19:24
duplicate of #270

**Closed by Paralusion** 2021-04-17 19:24 UTC
Labels: enhancement
