### ISSUE TITLE
Xray not hiding vegetation due to Sodium

### ISSUE THREAD

**Issue by TheRedHippo** [THEREALWWEFAN231/Inertia#628] opened 2020-08-04 07:42 UTC
**Inertia Utility Mod version:** 3.1
**Minecraft version:** 1.16.1
**Operating system:** Windows 10
**Optifine/Other mods:** Sodium

**What's the issue:** Xray doesn't hide all blocks- all flowers, grass, kelp, seaweed, and annoyingly the top of snow layers all continue to be displayed when Xray is on. It's definitely possible to stop this, as one workaround is to bind BlockSpoof to the same key and spoof the blocks listed above to air.

**Comment by THEREALWWEFAN231** [comment] 2020-08-04 15:47
This is because of Sodium, its not high on my priority list.

**Comment by Paralusion** [comment] 2021-04-17 21:52
duplicate of #627

**Closed by Paralusion** 2021-04-17 21:52 UTC
Labels: bug

**Comment by feliscatusmeows** [comment] 2021-07-07 09:59
Wait, that's a completely different issue
