### ISSUE TITLE
bug my game crash crash report :The game crashed whilst rendering screen Error: java.lang.NullPointerException: Screen cannot be null Ukončovací kód: -1

### ISSUE THREAD

**Issue by test4514** [THEREALWWEFAN231/Inertia#1164] opened 2021-04-17 17:13 UTC
**Inertia Utility Mod version:** 
**Minecraft version:** 
**Operating system:** 
**Optifine/Other mods:** 

**What's the issue:** 

**Crash-report(if applicable)(Would be very useful also please format):**

**Final checklist:**

- [ ] I know how to properly use check boxes 
- [ ] I have tried to reproduce this bug after removing all other mods except for Inertia. 
- [ ] I have attemped to reproduce this bug using the latest available release of Inertia.

**Comment by 0x150** [comment] 2021-04-17 17:17
can we like get the crash report or something

**Comment by Paralusion** [comment] 2021-04-17 17:31
duplicate of #1163

**Closed by Paralusion** 2021-04-17 17:31 UTC
Labels: bug
