### ISSUE TITLE
esp update suggestion

### ISSUE THREAD

**Issue by DeadAlice5094** [THEREALWWEFAN231/Inertia#879] opened 2020-11-17 16:46 UTC
**Minecraft Version(s)**
1.16.4~1.16.3

 Item esp

Can't just display certain items?

**Comment by THEREALWWEFAN231** [comment] 2020-11-17 17:15
*This is a really picky suggestion...*

**Comment by enderson0** [comment] 2020-11-18 20:37
It is theoretically possible as there is an NBT tag pertaining to specific items. In vanilla 
@e[type=minecraft:item,nbt={id:"ITEM HERE"}]
is a selector for individual items and could theoretically be used for ESP.

**Comment by THEREALWWEFAN231** [comment] 2020-11-18 21:15
I never said it was impossible, I just said it's quite picky.

**Comment by Paralusion** [comment] 2021-04-17 20:21
duplicate of #349

**Closed by Paralusion** 2021-04-17 20:21 UTC
Labels: enhancement
