### ISSUE TITLE
own text for .randombook suggestion

### ISSUE THREAD

**Issue by kielet** [THEREALWWEFAN231/Inertia#1101] opened 2021-02-24 10:58 UTC
Sorry for bothering again.
Inertia already has a .randombook but it does'nt let you type your own text file books.
It would be nice to be able to type actual stuff in the books

Bookbot that lets you write your own text files into books.

We could write books in minecraft

- [x] I know how to properly use check boxes 
- [x] This is not a suggestion for baritone or other mod

**Comment by kielet** [comment] 2021-02-24 11:00
Please

**Comment by constantinDev** [comment] 2021-02-24 11:24
so you want a bookbot that just writes your own copypasta into them..?

**Comment by kielet** [comment] 2021-02-24 11:25
Yes

**Comment by Paralusion** [comment] 2021-04-17 21:02
duplicate of #414

**Closed by Paralusion** 2021-04-17 21:02 UTC
Labels: enhancement
