### ISSUE TITLE
Suggestion: Add "Noclip"

### ISSUE THREAD

**Issue by kikogc153** [THEREALWWEFAN231/Inertia#981] opened 2020-12-27 09:46 UTC
**Minecraft Version(s)** 
1.12.2

**What is the suggestion**
I would like you to add "NoClip".

**Why would this feature be useful**
because it is a hack that is like going into gamemode 3 mode!

**Comment by DrAGoniPenguin** [comment] 2020-12-28 17:20
Just wondeirng, wouldn't that be something like freecam? Sometimes, if a server even has a plotsquared sort of plugin, and if the owner of a plot has to give permissions to let you build and break blocks, freecam can actually sometimes bypass and let you break and place things.
Or, something like phase (drop sand block on your head, I believe, to start,) can let you pass through walls.
That's a cool idea though btw

**Comment by constantinDev** [comment] 2020-12-29 10:06
> Just wondeirng, wouldn't that be something like freecam? Sometimes, if a server even has a plotsquared sort of plugin, and if the owner of a plot has to give permissions to let you build and break blocks, freecam can actually sometimes bypass and let you break and place things.
> 
> Or, something like phase (drop sand block on your head, I believe, to start,) can let you pass through walls.
> 
> That's a cool idea though btw

Freecam sends a break packet to the position of the block you are trying to break while the player is still in the original position. The suggestion here says that the player moves through continuous teleporting, effectively being able to phase into blocks, allowing for real travel in the world.

**Comment by kikogc153** [comment] 2020-12-29 11:25
That's what I'm explaining! Thanks

**Comment by Paralusion** [comment] 2021-04-17 18:48
duplicate of #88

**Closed by Paralusion** 2021-04-17 18:48 UTC
Labels: enhancement
