### ISSUE TITLE
Auto Jump

### ISSUE THREAD

**Issue by AutistEren** [THEREALWWEFAN231/Inertia#919] opened 2020-12-05 15:17 UTC
**What is the suggestion** Auto Walk but it jumps instead.

**Why would this feature be added**
- Easy to code
- Possible Anti AFK
- When farming mobs, it can crit hit them because on some servers criticals doesn't work.

**Comment by MLGgamingpro** [comment] 2020-12-05 18:21
hold space 😎 ez bypass 2020
probably wouldn't be useful anyways 😩

**Comment by AutistEren** [comment] 2020-12-05 18:29
*ahem* **AFK** mob farming

**Comment by MLGgamingpro** [comment] 2020-12-05 18:30
put literally anything on your space bar, and there are probably programs that can do that anyways

**Comment by AutistEren** [comment] 2020-12-05 18:31
but i do other stuff when im afk

**Comment by RocketNinja15** [comment] 2020-12-06 23:00
pp

**Comment by Paralusion** [comment] 2021-04-17 20:31
duplicate of #250

**Closed by Paralusion** 2021-04-17 20:31 UTC
Labels: enhancement
