### ISSUE TITLE
long jump and air jump.

### ISSUE THREAD

**Issue by Missing-entity** [THEREALWWEFAN231/Inertia#825] opened 2020-10-29 08:44 UTC
add a long jump and air jump. both fun and can bypass some anti che*ts.

**Comment by MLGgamingpro** [comment] 2020-10-29 15:22
Please follow the format.
Longjump would be helpful and definitely should be in Inertia air-jump is a duplicate of #639 #612 and #88. I highly doubt air-jump this could bypass any anti-cheats though.

**Comment by Paralusion** [comment] 2021-04-17 19:27
thanks @MLGgamingpro : duplicate of #88

**Closed by Paralusion** 2021-04-17 19:27 UTC
