### ISSUE TITLE
 Auto shield creeper/skeleton/arrows Suggestion

### ISSUE THREAD

**Issue by ScubaCreator** [THEREALWWEFAN231/Inertia#738] opened 2020-09-14 00:22 UTC
Any version would be great I usually use 1.16.2

A cool feature would be a module that when turned on would automatically block with your shield when there is a creeper about to explode or an arrow about to hit you.

This feature would be useful when I play on a new server and I'm new so I can't tank a creeper hit if the difficulty is hard. Maybe I should just have better reaction time from my blocking but I feel like I always get snuck upon.

**Comment by MLGgamingpro** [comment] 2020-09-14 16:21
While this feature would be useful, I think it would be difficult to implement (for arrows) since it would have to predict where the arrow is going, and block in time, and you will also probably be moving while it happens. For creepers i don't think it would be to difficult since it would have to block when a creeper is in your radius. For now just turn on the option that shows sounds in the bottom left, or just use NoSlow and always block.

**Comment by Epikest** [comment] 2020-09-18 23:52
i already suggested this you can just search block aura then copy and paste your stuff

**Comment by Paralusion** [comment] 2021-04-17 19:41
duplicate of #116

**Closed by Paralusion** 2021-04-17 19:41 UTC
Labels: enhancement
