### ISSUE TITLE
Suggestion - FOV for Aim Assist

### ISSUE THREAD

**Issue by BoxFullOfInk** [THEREALWWEFAN231/Inertia#420] opened 2019-12-24 01:27 UTC
**Minecraft Version**
1.15.x
**What is the suggestion**
Add an fov slider to the Aim Assist when it's on Legit mode so it doesn't turn towards players that are directly behind the player/out of a certain fov.
**Why it will be useful**
It'll make legit mode look more legit.

**Comment by aesafdasfda** [comment] 2019-12-29 18:40
stop being poor and get Vape or drip if you want good legit crap

**Comment by THEREALWWEFAN231** [comment] 2019-12-29 18:41
> VAPE FOR 1.15 DRIP FOR 1.15 bruh we got some competition

**Comment by Paralusion** [comment] 2021-04-17 21:03
duplicate of #53

**Closed by Paralusion** 2021-04-17 21:03 UTC
