### ISSUE TITLE
Auto Jump

### ISSUE THREAD

**Issue by mehmetf0** [THEREALWWEFAN231/Inertia#977] opened 2020-12-25 18:28 UTC
Auto Jump. automaticly jump

**Comment by Autist69420** [comment] 2020-12-25 18:30
why would you want this, it serves no purpose. You can legit just put your phone on the spacebar, auto jump done without effort

**Comment by AutistEren** [comment] 2020-12-25 18:34
> why would you want this, it serves no purpose. You can legit just put your phone on the spacebar, auto jump done without effort

then there is no point on having auto walk too

**Comment by Autist69420** [comment] 2020-12-25 18:35
> > why would you want this, it serves no purpose. You can legit just put your phone on the spacebar, auto jump done without effort
> 
> then there is no point on having auto walk too

auto walk is more usefull then auto jump

**Comment by AutistEren** [comment] 2020-12-25 18:35
> > > why would you want this, it serves no purpose. You can legit just put your phone on the spacebar, auto jump done without effort
> > 
> > 
> > then there is no point on having auto walk too
> 
> auto walk is more usefull then auto jump

you cant sprint jump with auto walk

**Comment by Vorlice** [comment] 2020-12-27 20:57
There is Step but for some reason you want to jump in place?

**Comment by Vorlice** [comment] 2020-12-27 20:58
> > > > why would you want this, it serves no purpose. You can legit just put your phone on the spacebar, auto jump done without effort
> > > 
> > > 
> > > then there is no point on having auto walk too
> > 
> > 
> > auto walk is more usefull then auto jump
> 
> you cant sprint jump with auto walk

You can enable Speed which has b-hopping, normal jumping, and more/

**Comment by Paralusion** [comment] 2021-04-17 20:31
duplicate of #250

**Closed by Paralusion** 2021-04-17 20:31 UTC
Labels: enhancement
