### ISSUE TITLE
Enchant Cracker

### ISSUE THREAD

**Issue by RocketNinja15** [THEREALWWEFAN231/Inertia#990] opened 2020-12-30 04:33 UTC
**Minecraft Version(s)**
All
**What is the suggestion**
To integrate enchant cracker by earth computer. It is an open sourse enchantment cracker. It calculates the enchantment “seed” and when u drop the amount of items that it tells you, you can select exactly what enchantments you want on your sword.... imagine if intertia could could do this automatically 
**Why would this feature be useful**
Yes ... https://github.com/Earthcomputer/EnchantmentCracker

**Comment by feliscatusmeows** [comment] 2021-01-02 07:33
frick it just add all of clientcommands to inertia

**Comment by RocketNinja15** [comment] 2021-01-09 00:24
@THEREALWWEFAN231 ???

**Comment by JohnShiozo** [comment] 2021-01-09 00:26
pong

**Comment by Godwhitelight** [comment] 2021-01-19 11:06
bruh that is epic

**Comment by Paralusion** [comment] 2021-04-17 18:46
duplicate of #899

**Closed by Paralusion** 2021-04-17 18:46 UTC
Labels: enhancement
