### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by TheShadowGamer06** [THEREALWWEFAN231/Inertia#549] opened 2020-07-12 22:12 UTC
**Minecraft Version(s)**
For all current Inertia versions
**What is the suggestion**
Add an option in Kill Aura to not target tamed mobs
**Why would this feature be useful**
If you're using it to kill creepers or other hostile mobs nearby your horse, you don't accidentally hit or kill your horse.

**Comment by Paralusion** [comment] 2021-04-17 19:00
duplicate of #45

**Closed by Paralusion** 2021-04-17 19:00 UTC
Labels: enhancement
