### ISSUE TITLE
Death-Freecam / Zombie

### ISSUE THREAD

**Issue by MLGgamingpro** [THEREALWWEFAN231/Inertia#716] opened 2020-09-05 01:01 UTC
**Minecraft Version(s)** 1.12.2 - 1.16.2

**What is the suggestion** A DeathFreecam / Zombie Module

**Why would this feature be useful** It would allow you (or your camera) to move around while dead, allowing you to see who killed you, what they are doing etc. It would allow you to "spectate" a base being griefed by placing an alt, killing it and using ReplayMod or something to record it, this feature is in [Wolfram Client](https://www.wolframclient.net/) but since that it is no longer maintained, and is missing what I like about Inertia Utility Mod I would like to see it added here. (This was suggested in #529 and #111)

**Comment by Paralusion** [comment] 2021-04-17 19:39
duplicate of #111

**Closed by Paralusion** 2021-04-17 19:39 UTC
Labels: enhancement
