### ISSUE TITLE
"Steal" Button in Chest

### ISSUE THREAD

**Issue by AutistEren** [THEREALWWEFAN231/Inertia#746] opened 2020-09-20 15:05 UTC
**What is the suggestion** Steal button in chest/hopper/dropper etc. gui
Also an option to hide the button*

**Why would this feature be useful** Chest stealer steals everything without we not knowing whats inside, so we can decide if we want to steal it or not

**Comment by Paralusion** [comment] 2021-04-17 19:46
duplicate of #120

**Closed by Paralusion** 2021-04-17 19:46 UTC
Labels: enhancement
