### ISSUE TITLE
6+ block tp-aura

### ISSUE THREAD

**Issue by Lua51** [THEREALWWEFAN231/Inertia#363] opened 2019-11-11 03:00 UTC
**Minecraft Version**
1.14.4
**What is the suggestion**
There should be a module for tp-aura. Not just the normal tp-aura, but a tp-aura that slowly teleports to a victim, and hits them, and teleports back to where the user was originally standing. There should be options on how far it can be, how big the gap is when slowly teleporting, and how fast to teleport. Just like in jigsaw, but slightly better.
**Why it will be useful**
It will be useful to just mess around with players, or just be a dick.

**Comment by Paralusion** [comment] 2021-04-17 20:52
duplicate of #637

**Closed by Paralusion** 2021-04-17 20:52 UTC
Labels: enhancement
