### ISSUE TITLE
Orebfuscator

### ISSUE THREAD

**Issue by RocketNinja15** [THEREALWWEFAN231/Inertia#921] opened 2020-12-05 21:31 UTC
**Minecraft Version(s)**
alll
**What is the suggestion**
It would bypass the orebfuscator plugin... like many other clients have
**Why would this feature be useful**
because anti-xray is bad....

**Comment by THEREALWWEFAN231** [comment] 2020-12-05 22:17
"like many other clients have" tell me another client beside future that has it... 😳

**Comment by AutistEren** [comment] 2020-12-05 22:20
fart client

**Comment by RocketNinja15** [comment] 2020-12-06 00:31
Still... pls

________________________________

**Comment by RocketNinja15** [comment] 2020-12-06 23:00
@THEREALWWEFAN231 still doe... its finenenee

**Comment by constantinDev** [comment] 2020-12-29 10:19
I made a mod for that

**Comment by Paralusion** [comment] 2021-04-17 19:12
duplicate of  #42

**Closed by Paralusion** 2021-04-17 19:12 UTC
Labels: enhancement
