### ISSUE TITLE
AirJump

### ISSUE THREAD

**Issue by Beanthief** [THEREALWWEFAN231/Inertia#710] opened 2020-09-02 03:43 UTC
**Minecraft Version(s)**
1.16.2+
**What is the suggestion**
Add an airjump or doublejump feature.
**Why would this feature be useful**
It would make traversing vertical terrain easier in survival mode. I can also use it to debug my anticheat better.

**Comment by MLGgamingpro** [comment] 2020-09-02 14:22
I think this would be a nice-to-have, i wouldn't see much point in it though, unless the server has no anti-cheat, also i don't think it should be for **only** 1.16.2+ i think its should be for 1.12.2+.

**Comment by GaiaAlexf** [comment] 2020-09-02 14:25
both #691 and #612 already have this, #612 being the first

**Comment by Paralusion** [comment] 2021-04-17 22:02
duplicate of  #88

**Closed by Paralusion** 2021-04-17 22:02 UTC
Labels: enhancement
