### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by AlmightyToast** [THEREALWWEFAN231/Inertia#1069] opened 2021-02-04 20:44 UTC
**Minecraft Version(s)**
1.12.2
**What is the suggestion**
Auto wither
**Why would this feature be useful**
To spawn withers automatically very quickly
**Final checklist:**

- [x] I know how to properly use check boxes 
- [x] This is not a suggestion for baritone or other mod

**Comment by Paralusion** [comment] 2021-04-17 18:19
duplicate of  #996

**Closed by Paralusion** 2021-04-17 18:19 UTC
Labels: enhancement
