### ISSUE TITLE
xray using seed

### ISSUE THREAD

**Issue by enderson0** [THEREALWWEFAN231/Inertia#862] opened 2020-11-10 02:59 UTC
Basically xray that looks at xray through the lens of the seed through either chunkbase or a clone world and ignores blocks that aren't stone. Basically the solution to failed / overloaded xray but wouldn't work on worlds with custom generation (or old generation[bypass: checks the chunk and copies the version and does the same])

I have a custom mod group and one of them adds an anti xray and I want to see the ores cause I see the fake ores even in creative...

**Comment by GaiaB0t** [comment] 2020-11-10 03:05
baritone is a separate component than inertia, wwefan just adds it to inertia, so if you want "bettertone" you'd need to talk to the baritone devs/make a similar suggestion on there, but it'd probably be rejected immediately

**Comment by Paralusion** [comment] 2021-04-17 19:13
honestly would need to calculate a lot of stuff and it'd be very heavy on performance; better to add orebfuscator bypass, so duplicate of  #42

**Closed by Paralusion** 2021-04-17 19:13 UTC
Labels: enhancement
