### ISSUE TITLE
Smarter aura

### ISSUE THREAD

**Issue by SylveonBottle** [THEREALWWEFAN231/Inertia#100] opened 2019-07-16 17:24 UTC
**Minecraft Version**
All that WWE supports
**What is the suggestion**
Make aura not attack mobs such as wolves, pigman, etc which will become aggressive
**Why it will be useful**
No more accidental whoopsies in nether when fighting skeletons

**Comment by Paralusion** [comment] 2019-07-16 21:42
duplicate of a issue i am too lazy to find

**Closed** 2021-01-27 18:31 UTC
Labels: enhancement
