### ISSUE TITLE
Option to hide "Inertia Options" button on the pause menu

### ISSUE THREAD

**Issue by SilverPNG** [THEREALWWEFAN231/Inertia#1134] opened 2021-03-28 12:30 UTC
**Minecraft Version(s)** All

**What is the suggestion** Title says it all, just an option or way (like a key bind, right Alt or something) to hide the inertia options, just so that when you accidentally press escape people cant see that your'e using the inertia utility mod, but instead just see a normal Minecraft pause menu.

**Why would this feature be useful** again just to be more sneaky

**Final checklist:**

- [x] I know how to properly use check boxes 
- [x] This is not a suggestion for baritone or other mod

**Comment by bigsecretofind** [comment] 2021-03-28 17:21
SIR THIS A UTILITY MOD NOT A HACKED CLIENT I REPEAT NOT A HACKED CLIENT THIS MEANT FOR ANARCHY SERVERS!
AND SERVERS THAT ALLOW THESE TYPES OF MODIFACTIONS

**Comment by Paralusion** [comment] 2021-03-28 17:31
this is not a mod made for malicious purposes

**Comment by feliscatusmeows** [comment] 2021-03-28 17:41
We have a feature that does that, you do .value chat_bot spammer true then do .t chat_bot
Doing those commands will unload inertia from minecraft.

**Comment by Paralusion** [comment] 2021-04-17 17:47
duplicate of  #270

**Closed by Paralusion** 2021-04-17 17:47 UTC
Labels: enhancement
