### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Kolders888** [THEREALWWEFAN231/Inertia#1149] opened 2021-04-09 11:42 UTC
**Minecraft Version(s)** 1.16.5 

**What is the suggestion** Add TP-Aura.

**Why would this feature be useful** It would be useful for anarchy pvp,sometimes.

**Final checklist:** 

 

- [   ] I know how to properly use check boxes 

- [ ] This is not a suggestion for baritone or other mod

**Comment by Paralusion** [comment] 2021-04-09 12:02
duplicate of like 10 other tp aura issues

**Comment by Paralusion** [comment] 2021-04-17 17:38
duplicate of #637

**Closed by Paralusion** 2021-04-17 17:38 UTC
Labels: enhancement
