### ISSUE TITLE
Suggestion for Kill Aura, ESP, etc.

### ISSUE THREAD

**Issue by AnimalTheGamer300** [THEREALWWEFAN231/Inertia#980] opened 2020-12-27 00:52 UTC
**Minecraft Version(s)**
1.16.4 and maybe below.

**What is the suggestion**
Choose specific entities for Kill Aura, ESP, and related.

**Why would this feature be useful**
For KA, it'd be useful because let's say you're in the nether with KA on and have it to attack Animals. You pass by a Hoglin _and_ Zombified Piglin, you can already see the chaos. You only want to attack the Hoglins since Zombified Piglins are not fun to deal with. I've also seen this feature on Meteor Client so why can't Inertia have it?

For ESP, let's say you're looking for cows so you enable ESP and have Animals, you'll see every single thing considered an Animal, so pigs, sheep, squids, etc. Yeah I know, the example isn't great but you get what I mean.

**Comment by THEREALWWEFAN231** [comment] 2020-12-27 00:54
It's going to be added sometime, when? I don't know. It's more complicated for Inertia then you would think, especially ESP.

**Comment by feliscatusmeows** [comment] 2020-12-27 01:43
Poor wwefan is going to be forced to make a gui for every entity.

**Comment by AnimalTheGamer300** [comment] 2020-12-27 06:31
Well, at least I know that sooner or later Inertia will have it. Also about the ESP stuff, I don't really care about it but I still decided to talk about it, I'm really only interested in the KA stuff.

**Comment by Paralusion** [comment] 2021-04-17 18:49
duplicate of  #27

**Closed by Paralusion** 2021-04-17 18:49 UTC
Labels: enhancement
