### ISSUE TITLE
Suggestion, TP aura

### ISSUE THREAD

**Issue by SirHaxe** [THEREALWWEFAN231/Inertia#1054] opened 2021-01-26 03:13 UTC
**Minecraft Version(s)** 1.16.4, but all TBH

**What is the suggestion** add a mode to killaura to just tp around the target attacking it

**Why would this feature be useful** makes PVP and PVE WAAAY easier!

**Final checklist:**

- [x] I know how to properly use check boxes 
- [x] This is not a suggestion for baritone or other mod

**Comment by feliscatusmeows** [comment] 2021-01-28 21:07
Incorrect, tp aura teleports around the target so that it's impossible to hit you. It is easy to detect. What you are describing is a type of reach bypass.

**Comment by Paralusion** [comment] 2021-04-17 18:23
duplicate of #637

**Closed by Paralusion** 2021-04-17 18:23 UTC
Labels: enhancement
