### ISSUE TITLE
Auto Mount

### ISSUE THREAD

**Issue by DortyTheGreat** [THEREALWWEFAN231/Inertia#942] opened 2020-12-10 06:31 UTC
**Minecraft Version(s)** ALL

**What is the suggestion** add AutoMount function

**Why would this feature be useful** some duplication glitches could be
recreated via this function

**Comment by Magzypotato** [comment] 2020-12-31 02:03
I would absolutely love this 😁

**Comment by Paralusion** [comment] 2021-04-17 21:41
duplicate of #536

**Closed by Paralusion** 2021-04-17 21:41 UTC
Labels: enhancement
