### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ShadowNinjaXD** [THEREALWWEFAN231/Inertia#1034] opened 2021-01-19 05:54 UTC
**all**

*Xray bypass, this would break blocks in a pattern revealing the real blocks*

**bypasses xray i mean, bro thats good :Dl**

**Final checklist:**

- [X] I know how to properly use check boxes 
- [X] This is not a suggestion for baritone or other mod

**Comment by ShadowNinjaXD** [comment] 2021-01-19 05:54
on a side note, i reallly dont know how to do this pls dont judge

**Comment by ShadowNinjaXD** [comment] 2021-01-19 05:54
i rarely use github

**Comment by constantinDev** [comment] 2021-01-19 11:13
Already made here: https://github.com/AriliusClient/AntiAntiXray

supports inertia and fabric, so you can just add it to your mods folder. `:aax help` to view help, `G` on your keyboard to scan blocks.

**Comment by constantinDev** [comment] 2021-01-19 11:13
Side note: `:aax scanall` if the server hides ores and doesnt obfuscate them. Takes longer tho

**Comment by Paralusion** [comment] 2021-04-17 18:29
duplicate of #42

**Closed by Paralusion** 2021-04-17 18:29 UTC
Labels: enhancement
