### ISSUE TITLE
Villager reroll

### ISSUE THREAD

**Issue by egsland** [THEREALWWEFAN231/Inertia#1109] opened 2021-03-03 21:03 UTC
Adding a automatic villager reroll would be nice, you just enter what book you want or what trade you want and it automatically rerolls until you get the book

**Comment by constantinDev** [comment] 2021-03-04 01:40
whos gonna tell him that villagers are server side because when i do ima break his heart

**Comment by Godeps2891** [comment] 2021-03-04 10:19
dupe of #741

**Closed by Godeps2891** 2021-03-04 10:19 UTC
