### ISSUE TITLE
Add antikick for flight which automatically toggles on and off super fast

### ISSUE THREAD

**Issue by Lobeatec** [THEREALWWEFAN231/Inertia#796] opened 2020-10-19 06:08 UTC
**Minecraft Version(s)**
All

**What is the suggestion**
To make flight automatically toggle on and off

**Why would this feature be useful**
Sometimes, they don't have anticheat but instead kick you for flight, (And I think its the same for nocheatplus) however its easily bypassed by just quickly turning on and off flight. this would make it so much easier to fly.

**Comment by AutistEren** [comment] 2020-10-19 06:10
already suggested think
maybe he will add it in 3.2

**Comment by zyrafal** [comment] 2020-10-19 12:01
It just needs to make go down a little bit, around 0.01blocks per second.

**Comment by THEREALWWEFAN231** [comment] 2020-10-19 15:36
Doesn't work exactly like that, vanilla will still kick you for flying for going down quite a bit per second.

**Comment by Paralusion** [comment] 2021-04-17 21:35
duplicate of  #505: thanks @MLGgamingpro

**Closed by Paralusion** 2021-04-17 21:35 UTC
Labels: enhancement
