### ISSUE TITLE
In some hacked clients suck as wurst there is a handnoclip feature and if possible it would be nice to see it added to inerta this feture allows you to reach selected blocks through walls such as chests hoppers notblocks ect.

### ISSUE THREAD

**Issue by mrblue1213** [THEREALWWEFAN231/Inertia#693] opened 2020-08-23 16:57 UTC
**Minecraft Version(s)**

**What is the suggestion**

**Why would this feature be useful**

**Comment by TheRedHippo** [comment] 2020-08-24 09:16
so ghosthand.
also please follow format

**Comment by MLGgamingpro** [comment] 2020-08-29 19:22
Inertia is not a "Hacked Client", i don't really see much point to this, it would be a nice to have but freecam works basically the same. Also like TheRedHippo said, please follow the format.

**Comment by feliscatusmeows** [comment] 2020-12-05 05:31
called ghost hand here. but adding a feature that auto reaches containers would be nice

**Comment by Paralusion** [comment] 2021-04-17 20:56
duplicate of  #376

**Closed by Paralusion** 2021-04-17 20:56 UTC
Labels: enhancement
