### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ergkhrhbrg** [THEREALWWEFAN231/Inertia#1147] opened 2021-04-08 14:38 UTC
**Minecraft Version(s)**
All of them
**What is the suggestion**
Add a zoom feature. Like what is in optifine. You could also use the scroll wheel while using zoom to zoom in and out. 
**Why would this feature be useful**
It would be really helpful to be able to see things far away. And the scroll feature is really nice depending on how faw away something is. 
**Final checklist:**

- [ ] I know how to properly use check boxes 
- [ ] This is not a suggestion for baritone or other mod

**Comment by Paralusion** [comment] 2021-04-17 17:42
duplicate of #584

**Closed by Paralusion** 2021-04-17 17:42 UTC
Labels: enhancement
