### ISSUE TITLE
the client needs a way to turn off

### ISSUE THREAD

**Issue by aries773** [THEREALWWEFAN231/Inertia#944] opened 2020-12-12 01:31 UTC
the client should have a setting in the minecraft menu to disable/enable it 
I like somethings in this client but most things are the same as the client I already  use 
but I would like to switch between the two for instance the other client I use has an on-off switch in the statistics  
so I would love if this client had something similar

**Comment by feliscatusmeows** [comment] 2020-12-12 02:24
Why would you need that? You could just to .t all_off.

**Comment by constantinDev** [comment] 2020-12-29 10:14
`.t all_off`

**Comment by Paralusion** [comment] 2021-04-17 17:40
merged with #1148, a button to disable Inertia entirely

**Comment by Paralusion** [comment] 2021-04-17 21:43
duplicate of #270

**Closed by Paralusion** 2021-04-17 21:43 UTC
