### ISSUE TITLE
AutoMount

### ISSUE THREAD

**Issue by MrEAZL** [THEREALWWEFAN231/Inertia#1130] opened 2021-03-18 10:45 UTC
**Minecraft Version(s)**
Every version

**What is the suggestion**
AutoMount to mount closest entity nearby automatically

**Why would this feature be useful**
It helps on duping on unpatched servers and it would be a cool feature in my opinion

**Final checklist:**

- [x] I know how to properly use check boxes 
- [X] This is not a suggestion for baritone or other mod

**Comment by Godeps2891** [comment] 2021-03-18 10:52
duplicate of #942

**Closed by Godeps2891** 2021-03-18 10:52 UTC
Labels: enhancement
