### ISSUE TITLE
AutoArmor Elytra Toggle

### ISSUE THREAD

**Issue by Fibalious** [THEREALWWEFAN231/Inertia#960] opened 2020-12-21 23:17 UTC
**Minecraft Version(s)**
1.9+

**What is the suggestion**
Add an option in AutoArmor to prioritize elytra or chestplate.

**Why would this feature be useful**
The only good way to switch between elytra and chestplates is with the Elytrareplace mod, which will make you drop your chestplate, because it hovers over your inventory when you toggle it.
In SMP, its very convenient to have 1 bind to switch between pvp and fly mode, especially because some mods you would use are incompatible (elytra+ elytrareplace & hunder no fall mods etc.)

**Comment by Paralusion** [comment] 2021-04-17 21:42
duplicate of  #546

**Closed by Paralusion** 2021-04-17 21:42 UTC
Labels: enhancement
