### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by MaxAdventures** [THEREALWWEFAN231/Inertia#1035] opened 2021-01-19 17:12 UTC
**3.1.3** 
**1.16.4** 
**Win 10** 
**Optifine/Other mods: nope** 

You can't use Feecam with Baritone :((

**Final checklist:**

- 

- [NO] I know how to properly use check boxes 
- [Yes] I have tried to reproduce this bug after removing all other mods except for Inertia. 
- [YES] I have attemped to reproduce this bug using the latest available release of Inertia.

**Comment by AutistEren** [comment] 2021-01-19 17:14
added in next update, not a bug, close the issue please

**Closed** 2021-01-19 17:15 UTC
Labels: bug

**Comment by feliscatusmeows** [comment] 2021-01-19 17:20
ya the freecam used to move the player instead of the camera :/
