### ISSUE TITLE
Flight Bypass Setting

### ISSUE THREAD

**Issue by ThePickinator** [THEREALWWEFAN231/Inertia#679] opened 2020-08-18 18:59 UTC
Minecraft version: All versions.

Suggestion: Anti kick fly setting.

Reason: Fly doesn't bypass "flying is disabled on this server". It often kicks me within about 5-10 seconds of using flight on any speed.

**Comment by MLGgamingpro** [comment] 2020-09-04 21:15
I would like to see this added. I've seen a *few* anarchy server without an anti-cheat.

**Comment by Paralusion** [comment] 2021-04-17 21:35
duplicate of  #505: thanks @MLGgamingpro

**Closed by Paralusion** 2021-04-17 21:35 UTC
Labels: enhancement
