### ISSUE TITLE
Timer Speed

### ISSUE THREAD

**Issue by enderson0** [THEREALWWEFAN231/Inertia#1001] opened 2021-01-05 19:19 UTC
https://streamable.com/uwvp81
In this video I compare all the speed modules to Timer at speed 6.0 (Vanilla at 6 BPS, NCP at 10 BPS, Packet at 13 BPS and Timer 6.0 at 26 BPS)
Timer is undoubtedly the fastest way to go on Spartan servers at least
So please add it because I know lots of anarchies use Spartan and Timer overall is a clunky experience with blocks falling apart, glitchy movement and much more

**Final checklist:**

- [x] I know how to properly use check boxes 
- [x] This is not a suggestion for baritone or other mod

**Comment by Paralusion** [comment] 2021-04-17 20:57
duplicate of  #377

**Closed by Paralusion** 2021-04-17 20:57 UTC
Labels: enhancement
