### ISSUE TITLE
Suggestion/Bug AFK Fishing using AutoFish

### ISSUE THREAD

**Issue by Vorlice** [THEREALWWEFAN231/Inertia#984] opened 2020-12-27 20:55 UTC
**Minecraft Version(s)**
1.16.4
**What is the suggestion**
When using autofish and autotool, autotool doesn't swap to a new fishing pole when the previous breaks.
**Why would this feature be useful**
Improve quality of life with afk fishing

**Comment by Paralusion** [comment] 2021-04-17 19:53
duplicate of #125

**Closed by Paralusion** 2021-04-17 19:53 UTC
Labels: enhancement
