### ISSUE TITLE
no lava+water overlay suggestion

### ISSUE THREAD

**Issue by danzaa** [THEREALWWEFAN231/Inertia#1150] opened 2021-04-09 15:16 UTC
**Minecraft Version(s)**
all
**What is the suggestion**
no lava+water overlay
**Why would this feature be useful**
going for a netherrite and seeing better
**Final checklist:**

- [x] I know how to properly use check boxes 
- [x] This is not a suggestion for baritone or other mod

**Comment by Paralusion** [comment] 2021-04-17 20:42
duplicate of  #287

**Closed by Paralusion** 2021-04-17 20:42 UTC
Labels: enhancement
