### ISSUE TITLE
Suggestion Anti-afk

### ISSUE THREAD

**Issue by ImSwordKing** [THEREALWWEFAN231/Inertia#25] opened 2019-06-19 21:50 UTC
**Minecraft Version**
Minecraft Forge 1.12.2,1.13.x,1.14.x
**What is the suggestion**
an anti-afk which is custom with auto-jump,auto-walk or only turn around and punches
**Why it will be useful**
anarchy servers like 2b2t or other server with a queue have an anti-afk plugin which kicks the player if they doesn't move. it can be helpful because you can't be kicked if the anti-afk is on

**Comment by Paralusion** [comment] 2019-06-20 21:35
Duplicate of #11

**Comment by Paralusion** [comment] 2019-07-05 12:59
can be closed, as it's a duplicate

**Closed** 2021-01-27 18:21 UTC
Labels: enhancement
