### ISSUE TITLE
Using  ESP Outline crashing the game

### ISSUE THREAD

**Issue by IBGE-Dev** [THEREALWWEFAN231/Inertia#567] opened 2020-08-01 05:52 UTC
Inertia Utility Mod version:3.1
Minecraft version:1.16.1
Operating system:
Optifine/Other mods:** 

What's the issue: I were changing the ESP for player from 2D Box for Outline and my game crashed, tried rejoining the server and crashed again.

Crash-report(Would be very useful also please format):
[crash-2020-08-01_01.45.19-client.txt](https://github.com/THEREALWWEFAN231/Inertia/files/5009896/crash-2020-08-01_01.45.19-client.txt)

**Comment by TheRedHippo** [comment] 2020-08-01 06:10
[crash-2020-08-01_16.05.24-client.txt](https://github.com/THEREALWWEFAN231/Inertia/files/5009911/crash-2020-08-01_16.05.24-client.txt)

**Comment by THEREALWWEFAN231** [comment] 2020-08-01 06:12
thank you both, please continue to report you crash logs that do not contain this "org.spongepowered.asm.mixin.injection.callback.CancellationException: The call method_23517 is not cancellable."

my only suggestion for now is to not use outline or shader esp option, I think they both cause that to happen, this will be fixed in the next bug fix update.

duplicate of #569

**Closed by THEREALWWEFAN231** 2020-08-01 06:12 UTC
Labels: bug
