### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by varrooonn** [THEREALWWEFAN231/Inertia#594] opened 2020-08-01 19:58 UTC
**Inertia Utility Mod version:** 
FORGE 1.12.2
**Minecraft version:**
1.12.2 
**Operating system:** 
windows 10 x64 bit architecture
**Optifine/Other mods:** 
optifine, salhack, Elementars B6.1
**What's the issue:** 
after the forgemmodloader does its job, the screen goes black. I think this is a **compatibility issue**

**Crash-report(Would be very useful also please format):**
NA- no crash, the screen just goes black.

**Comment by varrooonn** [comment] 2020-08-01 20:03
yeah defo a bug
just checked

**Comment by THEREALWWEFAN231** [comment] 2020-08-01 21:33
I assume it doesn't happen without the other mods, it might be a battle for the main menu? Where inertia is trying to change it but another mod is?

**Comment by THEREALWWEFAN231** [comment] 2020-08-02 04:00
Ok so, it isn't a battle for the main menu. I think i figured out what the issue was, so it's hopefully fixed in 3.1.1(should release "soon"), it could be GREAT if when 3.1.1 releases you could try it and tell me if it happens or not. Like i said though, I think I fixed it. Feel free to reopen this, to tell me your results.

**Closed by THEREALWWEFAN231** 2020-08-02 04:00 UTC
Labels: bug

**Comment by varrooonn** [comment] 2020-08-02 06:25
yh sure!

**Comment by varrooonn** [comment] 2020-08-02 06:26
I think it might be elementars and inertia lol

cuz Elementars has like buttons for 2b2t and 2b2tpvp
could be...

**Comment by varrooonn** [comment] 2020-08-02 07:20
no it is a glitch with inertia and optifine

**Comment by THEREALWWEFAN231** [comment] 2020-08-02 07:29
Are you sure, try only inertia no optifine but like I said it should be fixed in the next update

**Comment by varrooonn** [comment] 2020-08-02 07:32
yh i did
and only inertia does that

**Comment by slashsynapse** [comment] 2020-10-24 04:05
@THEREALWWEFAN231  The problem is that inertia tries to load shaders, because open GL said my gpu supports it, but opengl is kind of unable to, and it does the black screen.

**Comment by slashsynapse** [comment] 2020-10-24 04:06
This is also the case I had with another utility mod, which was fixed.

**Comment by THEREALWWEFAN231** [comment] 2020-10-24 04:21
I am aware that is part of the issue, but the fact is minecraft spectral arrow affect is a shader and that works, so I have to find why my shader doesn't work but the spectral arrow does. I half way know why but its stupid.

**Comment by slashsynapse** [comment] 2020-10-24 05:59
ok xD
it sucks because I cannot use inertia 1.12.2
