### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by AcePixels** [THEREALWWEFAN231/Inertia#703] opened 2020-08-29 23:17 UTC
**Minecraft Version(s)**
1.16.1 - 1.16.2 
**What is the suggestion**
TP-Aura
**Why would this feature be useful**
because other clients have it and this one lacks it, and if you add it that makes your client more superior compared to say wurst, wurst client has some good killaura but it doesnt have crystal aura and it doesnt have anything else good, the only thing good it has is tpaura, so i figured if you would add that to the client you would be the #1 choice for 1.16.1 hacked clients

**Comment by THEREALWWEFAN231** [comment] 2020-08-29 23:18
Inertia is a utility mod not a hacked client, but ill probably add this sometime as i guess 1/4 of players play vanilla.

**Comment by MLGgamingpro** [comment] 2020-08-29 23:19
you *could* use the two clients at the same time but, be careful as mixing client can cause alot of, unintended consequences

**Comment by Paralusion** [comment] 2021-04-17 18:11
duplicate of #637

**Closed by Paralusion** 2021-04-17 18:11 UTC
Labels: enhancement
