### ISSUE TITLE
Black screen after loading

### ISSUE THREAD

**Issue by MrDevPosting** [THEREALWWEFAN231/Inertia#1212] opened 2021-05-26 22:01 UTC
**Inertia Utility Mod version:3.1.3** 
**Minecraft version:1.12.2**
**Operating system: Windows10**
**Optifine/Other mods: Optifine**
**Launcher:LauncherFenix 5.7.8-5**

**What's the bug:Black Screen after loading.**
**Photos**:
![image](https://user-images.githubusercontent.com/84835153/119736794-463b1080-be4c-11eb-9eff-0e135689132e.png)

Crash-report(if applicable)(located in .minecraft/latest.log):
[latest.log](https://github.com/THEREALWWEFAN231/Inertia/files/6549819/latest.log)

(game not crashing, i close it)
Final checklist:
- [x] I know how to properly use check boxes. 
- [x] I have tried to reproduce this bug after removing all other mods, including Optifine or Sodium. 
- [x] I have attemped to reproduce this bug using the latest available release of Inertia

**Comment by Godeps2891** [comment] 2021-05-26 22:32
known bug, should be fixed in the next update(no ETA), for now you'll have to use inertia for a different version of minecraft and use viaversion to connect to 1.12 servers

**Closed by Godeps2891** 2021-05-26 22:32 UTC

**Comment by feliscatusmeows** [comment] 2021-05-27 16:04
duplicate of #618 , also cracked/pirated launchers such as LauncherFenix aren't supported.
