### ISSUE TITLE
KillAura: "Random Aim"

### ISSUE THREAD

**Issue by SylveonBottle** [THEREALWWEFAN231/Inertia#157] opened 2019-07-19 18:55 UTC
**What is the suggestion**
Killaura: Remove "Body Part", replace with "Random Aim" to look legit
Similar to #143 
**Why it will be useful**
You won't be snapping to a single body part

**Comment by Paralusion** [comment] 2019-08-04 23:50
wwe is not a ghost client

**Comment by Paralusion** [comment] 2021-04-17 20:04
duplicate of #143

**Closed by Paralusion** 2021-04-17 20:04 UTC
Labels: enhancement
