### ISSUE TITLE
Anti kick and bypass.

### ISSUE THREAD

**Issue by Ral721chanel** [THEREALWWEFAN231/Inertia#823] opened 2020-10-28 10:05 UTC
Put a function on the fly so that when you use it, the minecraft server will not kick you.
Because in most of the servers in general and anarchic when using the fly for a long time they kick you. And the message "Fly is not avaible on this server" appears. But it is allowed.
And create a fly / speed bypass for the 2b2t and l2x9 servers.

**Comment by MLGgamingpro** [comment] 2020-11-01 14:27
Please follow the format.
Duplicate of #824, #796, #679,and #505.

**Comment by Paralusion** [comment] 2021-04-17 21:35
duplicate of  #505: thanks @MLGgamingpro

**Closed by Paralusion** 2021-04-17 21:35 UTC
